apiVersion: v1
kind: Service
metadata:
  name: devops-test
  labels:
    app: devops-test
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: devops-test
    protocol: TCP
  - name: "443"
    port: 443
    targetPort: devops-test
    protocol: TCP
  selector:
    app: devops-test
  type: LoadBalancer